//Enable MongoDB driver library
const mongoose = require('mongoose');

//Defines how the data should be (id generated by mongoose)
const espacio1Schema=mongoose.Schema({
    _id:mongoose.Schema.Types.ObjectId,
    attribute1:String,
    attribute2:Number
});

module.exports=mongoose.model("Espacio1",espacio1Schema);